name: Aqua Trivy Security Scan

on:
  push:
    branches:
      - master

jobs:
  scan:
    name: Trivy Security Scan
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v3

      # Step 2: Install Trivy
      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
          sudo mv ./bin/trivy /usr/local/bin

      # Step 3: Verify Trivy Installation
      - name: Verify Trivy Installation
        run: trivy --version

      # Step 4: Run Trivy Scan
      - name: Run Trivy Scan
        run: |
          mkdir -p scan-reports
          trivy fs --scanners vuln,config,secret --format table . > scan-reports/trivy-scan.txt

      # Step 5: Upload the Trivy Scan Report
      - name: Upload Trivy Scan Report
        uses: actions/upload-artifact@v3
        with:
          name: Trivy Scan Report
          path: scan-reports/trivy-scan.txt
