name: Aqua Trivy Security Scan

on:
  push:
    branches:
      - master

jobs:
  scan:
    name: Trivy Security Scan
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v3

      # Step 2: Install Trivy
      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh

      # Step 3: Run Trivy to scan the repository
      - name: Run Trivy Scan
        run: |
          mkdir -p scan-reports
          trivy fs --scanne

